[workspace]
members = ["crates/spidermonkey-embedding-splicer"]
exclude = [
  "deps/js-compute-runtime/runtime/js-compute-runtime/rust-url",
  "deps/js-compute-runtime/runtime/js-compute-runtime/rust-encoding"
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
bitflags = "1.3.2"
env_logger = "0.10.0"
heck =  { version = "0.4", features = ["unicode"] }
js-component-bindgen = { version = "1.0.0", no-default-features = ["transpile-bindgen"] }
pulldown-cmark = { version = "0.8", default-features = false }
walrus = "0.20.3"
wasm-encoder = "0.40.0"
wasmparser = "0.120.0"
wasmprinter = "0.2.77"
wat = "1.0.84"
wit-bindgen = "0.16.0"
wit-bindgen-core = "0.16.0"
wit-component = { version = "0.20.0", features = ["dummy-module"] }
wit-parser = "0.13.1"
